
#ifndef _RISCDUINO_TIMER_H
#define _RISCDUINO_TIMER_H

#define TIMER_GLBL_CFG      (0x00)  // TIMER GLBL CONFIG
#define TIMER_TIMET0_CFG    (0x04)  // TIMER0 CONFIG
#define TIMER_TIMET1_CFG    (0x08)  // TIMER0 CONFIG
#define TIMER_TIMET2_CFG    (0x0C)  // TIMER0 CONFIG

#define TIMER_MICRO_STEP     0x00   // TIMER STEP in MICRO SECOND 
#define TIMER_MILLI_STEP     0x01   // TIMER STEP in MILLI SECOND 
#define TIMER_SECOND_STEP    0x10   // TIMER STEP in SECOND 

#endif /* _RISCDUINO_GPIO_H */
